sonar.projectKey=hms_backend
sonar.projectName=hms_backend
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sqp_41e44590620f690fb55da5c675401f067a3df1b0