const Patient = require('../models/patient');

// ─────────────────────────────────────────────────────────────
//  POST /api/patients/create
//  Access : ADMIN | RECEPTIONIST only
// ─────────────────────────────────────────────────────────────
const createPatient = async (req, res) => {
    try {

        // ── 1. ROLE GUARD ─────────────────────────────────────────────────────
        // req.user is injected by your JWT / auth middleware
        const allowedRoles = ['Admin', 'Receptionist'];

        if (!req.user || !allowedRoles.includes(req.user.role)) {
            return res.status(403).json({
                success: false,
                message: 'Access denied. Only Admin or Receptionist can create patients.',
            });
        }

        // ── 2. EXTRACT BODY FIELDS ────────────────────────────────────────────
        const { name, phone, email, gender, dob, address, emergencyContact, status } = req.body;

        // ── 3. REQUIRED FIELD VALIDATION ──────────────────────────────────────
        if (!name || !phone || !email || !gender || !dob || !status) {
            return res.status(400).json({
                success: false,
                message: 'name, phone, email, gender, dob, and status are required.',
            });
        }

        // ── 4. VALIDATE GENDER ────────────────────────────────────────────────
        const allowedGenders = ['MALE', 'FEMALE'];
        if (!allowedGenders.includes(gender.toUpperCase())) {
            return res.status(400).json({
                success: false,
                message: `Invalid gender. Allowed values: ${allowedGenders.join(', ')}`,
            });
        }

        // ── 5. VALIDATE STATUS ────────────────────────────────────────────────
        const allowedStatuses = ['Active', 'Inactive'];
        if (!allowedStatuses.includes(status)) {
            return res.status(400).json({
                success: false,
                message: `Invalid status. Allowed values: ${allowedStatuses.join(', ')}`,
            });
        }

        // ── 6. VALIDATE DATE OF BIRTH ─────────────────────────────────────────
        const dateOfBirth = new Date(dob);
        if (isNaN(dateOfBirth.getTime())) {
            return res.status(400).json({
                success: false,
                message: 'Invalid date format for dob.',
            });
        }

        // dob must be in the past (can't be born in the future)
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        if (dateOfBirth >= today) {
            return res.status(400).json({
                success: false,
                message: 'Date of birth must be in the past.',
            });
        }

        // ── 7. VALIDATE PHONE FORMAT (10-digit) ───────────────────────────────
        const phoneRegex = /^[0-9]{10}$/;
        if (!phoneRegex.test(phone.trim())) {
            return res.status(400).json({
                success: false,
                message: 'Invalid phone number. Must be exactly 10 digits.',
            });
        }

        // ── 8. VALIDATE EMAIL FORMAT ──────────────────────────────────────────
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(email.trim())) {
            return res.status(400).json({
                success: false,
                message: 'Invalid email format.',
            });
        }

        // ── 9. CHECK DUPLICATE EMAIL ──────────────────────────────────────────
        const existingEmail = await Patient.findOne({ email: email.trim().toLowerCase() });
        if (existingEmail) {
            return res.status(409).json({
                success: false,
                message: 'A patient with this email already exists.',
            });
        }

        // ── 10. CHECK DUPLICATE PHONE ─────────────────────────────────────────
        const existingPhone = await Patient.findOne({ phone: phone.trim() });
        if (existingPhone) {
            return res.status(409).json({
                success: false,
                message: 'A patient with this phone number already exists.',
            });
        }

        // ── 11. CREATE PATIENT ────────────────────────────────────────────────
        //  patientUhid is auto-generated by pre('save') hook → PAT-000001
        const newPatient = new Patient({
            name: name.trim(),
            phone: phone.trim(),
            email: email.trim().toLowerCase(),
            gender: gender.toUpperCase(),
            dob: dateOfBirth,
            address: address ? address.trim() : undefined,
            emergencyContact: emergencyContact ? emergencyContact.trim() : undefined,
            status: status
        });

        const savedPatient = await newPatient.save();

        // ── 12. RESPOND ───────────────────────────────────────────────────────
        return res.status(201).json({
            success: true,
            message: 'Patient created successfully.',
            data: savedPatient,
        });

    } catch (error) {
        console.error('createPatient error:', error);
        return res.status(500).json({
            success: false,
            message: 'Internal server error.',
            error: error.message,
        });
    }
};

module.exports = { createPatient };
